emn/alerts/urls.py
from django.conf.urls import url

from contrib.views import autocomplete_view

from .models import Substance, Reaction
from .views import AlertCreateView, AlertListView, AlertDeleteView, AlertUpdateView

urlpatterns = [
    url(r'^insertar/$', AlertCreateView.as_view(), name='create-alert'),
    url(r'^listar/$', AlertListView.as_view(), name='list-alert'),
    url(r'^editar/(?P<pk>[0-9]+)/$', AlertUpdateView.as_view(), name='edit-alert'),
    url(r'^borrar/(?P<pk>[0-9]+)/$', AlertDeleteView.as_view(), name='delete-alert'),
    url(r'^substance/$', autocomplete_view, {'model': Substance}, name='substance'),
    url(r'^reaction/$', autocomplete_view, {'model': Reaction}, name='reaction'),
]

emn/emn/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^usuarios/', include('users.urls', namespace='users')),
    url(r'^', include('dashboard.urls', namespace='dashboard')),
    url(r'^paciente/', include('patients.urls', namespace='patients')),
    url(r'^paciente/enfermedades/', include('problems.urls', namespace='problems')),
    url(r'^paciente/alertas/', include('alerts.urls', namespace='alerts')),
    url(r'^paciente/procedimientos/', include('procedures.urls', namespace='procedures')),
    url(r'^paciente/medicamentos/', include('medications.urls', namespace='medications')),
    url(r'^paciente/historia-familiar/', include('familyhistory.urls', namespace='familyhistory')),
    url(r'^personal/paciente/', include('personnel.urls', namespace='personnel')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

emn/alerts/models.py
# -*- coding: utf-8 -*-
from django.db import models

from patients.models import Patient

# Create your models here.
# <thead>
#   <tr><th>Substance</th><th>Reaction</th><th>Status</th></tr>
# </thead>
# <tbody>
#   <tr><td>Penicillin</td><td>Hives</td><td>Active</td></tr>
#   <tr><td>Aspirin</td><td>Wheezing</td><td>Active</td></tr>
#   <tr><td>Codeine</td><td>Nausea</td><td>Active</td></tr>
# </tbody>


class Substance(models.Model):

    class Meta:
        verbose_name = "Sustancia"
        verbose_name_plural = "Sustancias"

    name = models.CharField(max_length=250, unique=True, verbose_name="Nombre")
    code = models.CharField(max_length=250, unique=True, verbose_name="Código")

    def __str__(self):
        return self.name


class Reaction(models.Model):

    class Meta:
        verbose_name = "Reacción"
        verbose_name_plural = "Reacciones"

    name = models.CharField(max_length=250, unique=True, verbose_name="Nombre")

    def __str__(self):
        return self.name


ACTIVE_FEED = 'A'
INACTIVE_FEED = 'I'

STATUS_CHOICES = (
    (ACTIVE_FEED, 'Activo'),
    (INACTIVE_FEED, 'Inactivo'),
)


class AllergiesAdverseReactionAlert(models.Model):

    class Meta:
        verbose_name = "Allergies, Adverse Reaction, Alert"
        verbose_name_plural = "Allergies, Adverse Reaction, Alerts"

    patient = models.ForeignKey(Patient, null=True)
    substance = models.CharField(max_length=250, verbose_name="Substancia")
    substance_code = models.CharField(max_length=250, verbose_name="", blank=True, null=True)
    reaction = models.CharField(max_length=250, verbose_name="Reacción", blank=True, null=True)
    status = models.CharField(max_length=250,
                              choices=STATUS_CHOICES,
                              default=ACTIVE_FEED,
                              verbose_name="Estatus")
    private = models.BooleanField(
        default=True,
        verbose_name="Estado",
        )

    def __str__(self):
        return self.substance

emn/alerts/forms.py
# -*- coding: utf-8 -*-
from .models import AllergiesAdverseReactionAlert

from django.forms.widgets import HiddenInput

from django.forms import ModelForm, RadioSelect, TypedChoiceField


class AlertsCreateUpdateForm(ModelForm):
    """
    Form that creates and edits patient`s Allergies, Adverse Reactions, Alerts
    """

    YESNO_CHOICES = (('0', 'Compartido'), ('1', 'Privado'))
    private = TypedChoiceField(choices=YESNO_CHOICES, widget=RadioSelect, label='Estado',
                               help_text='La información marcada como privada no puede ser accedida por el personal médico')

    class Meta:

        model = AllergiesAdverseReactionAlert
        fields = ('substance',
                  'substance_code',
                  'reaction',
                  'status',
                  'private',)

        widgets = {'substance_code': HiddenInput}

emn/alerts/views.py
from django.views.generic import CreateView, ListView, UpdateView, DeleteView

from django.core.urlresolvers import reverse_lazy

from django.db import transaction

from django.contrib.messages.views import SuccessMessageMixin

from patients.models import Patient

from contrib.views import AddPatientCreateMixin, ListPatientObjectsMixin, AlertMessagesMixin, CheckPatientMixin

from logs.views import RegisterActionMixing

from .models import AllergiesAdverseReactionAlert

from .forms import AlertsCreateUpdateForm
# Create your views here.


class AlertCreateView(CheckPatientMixin, SuccessMessageMixin, AlertMessagesMixin, RegisterActionMixing, AddPatientCreateMixin, CreateView):
    model_class = AllergiesAdverseReactionAlert
    template_name = 'alerts/create-edit.html'
    form_class = AlertsCreateUpdateForm
    success_url = reverse_lazy('alerts:list-alert')
    success_message = "%(substance)s fue creado satisfactoriamente"


class AlertListView(CheckPatientMixin, AlertMessagesMixin, ListPatientObjectsMixin, ListView):
    model = AllergiesAdverseReactionAlert
    template_name = 'alerts/list.html'
    context_object_name = 'alerts'


class AlertUpdateView(CheckPatientMixin, AlertMessagesMixin, SuccessMessageMixin, RegisterActionMixing, UpdateView):
    model = AllergiesAdverseReactionAlert
    template_name = 'alerts/create-edit.html'
    form_class = AlertsCreateUpdateForm
    success_url = reverse_lazy('alerts:list-alert')
    success_message = "%(substance)s fue editado satisfactoriamente"

class AlertDeleteView(DeleteView):
    model = AllergiesAdverseReactionAlert
    success_url = reverse_lazy('alerts:list-alert')

emn/alerts/templates/alerts/create-edit.html
{% extends "emn/base.html" %}
{% load bootstrap3 %}

{% block title %}Insertar o Editar Alerta {% endblock title %}

{% block content %}
    
            <form  id="alerts" method="POST">
                {% csrf_token %}
                <h1>Alertas, Alergias y Reacciones adversas</h1>
                <div>
                    {% bootstrap_form form  %}
                </div>
                <div>
                    <button type="submit" class="btn btn-default">Guardar Cambios</button>
                </div>
                
                <div class="clearfix"></div>
            </form>

{% endblock content %}


{% block pagejs %}
<script>
    $.validator.setDefaults({
        highlight: function(element) {
            $(element).closest('.form-group').addClass('has-error');
        },
        unhighlight: function(element) {
            $(element).closest('.form-group').removeClass('has-error');
        },
        errorElement: 'span',
        errorClass: 'help-block',
        errorPlacement: function(error, element) {
            private = $("#id_private_0")
            if(element.contains(private)){
                error.insertBefore(element.parent());
                console.log(element)
            }
            else {
                console.log(element)
            
                if(element.parent('.input-group').length) {
                    error.insertAfter(element.parent());
                } else {
                    error.insertAfter(element);
                }
            }
        }
    });
    $("#alerts").validate({
    });
    $(document).ready(function() {
        jQuery.extend(jQuery.validator.messages, {
            required: "Este campo es obligatorio.",
            remote: "Por favor, rellena este campo.",
            email: "Por favor, escribe una dirección de correo válida",
            url: "Por favor, escribe una URL válida.",
            date: "Por favor, escribe una fecha válida.",
            dateISO: "Por favor, escribe una fecha (ISO) válida.",
            number: "Por favor, escribe un número entero válido.",
            digits: "Por favor, escribe sólo dígitos.",
            creditcard: "Por favor, escribe un número de tarjeta válido.",
            equalTo: "Por favor, escribe el mismo valor de nuevo.",
            accept: "Por favor, escribe un valor con una extensión aceptada.",
            maxlength: jQuery.validator.format("Por favor, no escribas más de {0} caracteres."),
            minlength: jQuery.validator.format("Por favor, no escribas menos de {0} caracteres."),
            rangelength: jQuery.validator.format("Por favor, escribe un valor entre {0} y {1} caracteres."),
            range: jQuery.validator.format("Por favor, escribe un valor entre {0} y {1}."),
            max: jQuery.validator.format("Por favor, escribe un valor menor o igual a {0}."),
            min: jQuery.validator.format("Por favor, escribe un valor mayor o igual a {0}.")
        });

    });

    $("#id_substance").autocomplete({
        source: "{% url 'alerts:substance' %}", autoFocus: true,
        minLength: 2,
        select: function( event, ui) {
            $("#id_substance").val( ui.item.value );
            $("#id_substance_code").val( ui.item.code );
            return false;
        },
        search: function() {
            $("#id_substance_code").val('');            
        },
        changeL: function() {
            $("#id_substance_code").val('');            
        },
    });
    $("#id_reaction").autocomplete({
        source: "{% url 'alerts:reaction' %}", autoFocus: true,
        minLength: 2,
        select: function( event, ui) {
            $("#id_reaction").val( ui.item.value );
            return false;
        },
    });

</script>
{% endblock pagejs %}

emn/alerts/templates/alerts/list.html
{% extends "emn/base.html" %} 
{% load bootstrap3 %} 
{% load static %}

{% block pagecss %}

{% endblock pagecss %}
{% block title %} Listar Alertas {% endblock title %}
{% block content %}
        <div class="x_panel">
            <div class="x_title">
                <h2>Alertas, Alergias y Reacciones adversas</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a href="{% url 'alerts:create-alert' %}"><i class="fa fa-plus"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="table-responsive">
                <table class="table table-striped table-hover" id="table-alert">
                    <thead>
                        <th>Substancia</th>
                        <th>Código</th>
                        <th>Estado</th>                                              
                        <th>Reacción</th>
                        <th>Estatus</th>
                        <th>Acciones</th>
                    </thead>
                    <tbody>
                        {% for alert in alerts %}
                        <tr>
                            <td>{{ alert.substance }}</td>
                            <td>{{ alert.substance_code }}</td>
                            {% if  alert.private == True %}
                            <td>Privado</td>                                                        
                            {% else %}
                            <td>Compartido</td>
                            {% endif %}
                            <td>{{ alert.reaction }}</td>
                            <td>{{ alert.get_status_display }}</td>
                            <td>
                                 <div class="dropdown">
                                    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Acciones
                                    <span class="caret"></span></button>
                                    <ul class="dropdown-menu">
                                        <li><a href="#" class="delete-object" data-target="#deleteModal" data-toggle="modal" data-url-delete="{% url 'alerts:delete-alert' alert.pk %}">Eliminar</a></li>
                                        <li><a href="{% url 'alerts:edit-alert' alert.pk %}">Editar</a></li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
<div id="deleteModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Eliminar</h4>
            </div>
            <div class="modal-body">
                <p>¿Está seguro de que desea eliminar permanentemente el elemento especificado? </p>
                <form method="POST" id="form-del" action="">
                {% csrf_token %}
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                        <input type="submit" class="btn btn-danger" value="Eliminar">
                    </div>
                </form>
            </div>
            
        </div>
    </div>
</div>

{% endblock content %}

{% block pagejs %}
<script type="text/javascript"> 
    $(document).ready(function () {
        $(".delete-object").click( 
            function(){
                $(this).attr('data-url-delete');
                $('#form-del').attr('action', $(this).attr('data-url-delete'));
            }
        )
    });   
</script>
{% endblock pagejs %}