emn/emn/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^usuarios/', include('users.urls', namespace='users')),
    url(r'^', include('dashboard.urls', namespace='dashboard')),
    url(r'^paciente/', include('patients.urls', namespace='patients')),
    url(r'^paciente/enfermedades/', include('problems.urls', namespace='problems')),
    url(r'^paciente/alertas/', include('alerts.urls', namespace='alerts')),
    url(r'^paciente/procedimientos/', include('procedures.urls', namespace='procedures')),
    url(r'^paciente/medicamentos/', include('medications.urls', namespace='medications')),
    url(r'^paciente/historia-familiar/', include('familyhistory.urls', namespace='familyhistory')),
    url(r'^personal/paciente/', include('personnel.urls', namespace='personnel')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

emn/familyhistory/urls.py
from django.conf.urls import url
from contrib.views import autocomplete_view
from .models import Diagnosis
from .views import (RelativeCreateView, RelativeListView, RelativeUpdateView, RelativeDeleteView,
                    FamilyHistoryCreateView, FamilyHistoryUpdateView, FamilyHistoryDeleteView)

urlpatterns = [
    url(r'^insertar/$', FamilyHistoryCreateView.as_view(), name='create-familyhistory'),
    url(r'^editar/(?P<pk>[0-9]+)/$', FamilyHistoryUpdateView.as_view(), name='edit-familyhistory'),
    url(r'^borrar/(?P<pk>[0-9]+)/$', FamilyHistoryDeleteView.as_view(), name='delete-familyhistory'),
    url(r'^familiar/insertar/$', RelativeCreateView.as_view(), name='create-relative'),
    url(r'^familiar/listar/$', RelativeListView.as_view(), name='list-relative'),
    url(r'^familiar/editar/(?P<pk>[0-9]+)/$', RelativeUpdateView.as_view(), name='edit-relative'),
    url(r'^familiar/borrar/(?P<pk>[0-9]+)/$', RelativeDeleteView.as_view(), name='delete-relative'),
    url(r'^diagnosis/$', autocomplete_view, {'model': Diagnosis}, name='diagnosis'),

]

emn/familyhistory/models.py
# -*- coding: utf-8 -*-
from django.db import models

from patients.models import Patient

# Create your models here.

# <paragraph>Father (deceased)</paragraph>
#   <table border="1" width="100%">
#       <thead>
#           <tr><th>Diagnosis</th><th>Age At Onset</th></tr>
#       </thead>
#       <tbody>
#           <tr><td>Myocardial Infarction (cause of death)</td><td>57</td></tr>
#           <tr><td>Hypertension</td><td>40</td></tr>
#       </tbody>
#   </table>
#   <paragraph>Mother (alive)</paragraph>
#   <table border="1" width="100%">
#       <thead>
#           <tr><th>Diagnosis</th><th>Age At Onset</th></tr>
#       </thead>
#       <tbody>
#           <tr><td>Asthma</td><td>30</td></tr>
#       </tbody>
#  </table>

# TO-DO


class Diagnosis(models.Model):

    class Meta:
        verbose_name = "Diagnóstico"
        verbose_name_plural = "Diagnósticos"

    name = models.CharField(max_length=250, unique=True, verbose_name="Nombre")
    code = models.CharField(max_length=250, unique=True, verbose_name="Código")

    def __str__(self):
        return self.name


FATHER = 'F'
MOTHER = 'M'
SIBLING = 'S'
SONS = 'A'
GRAMPS = 'G'
GRANDCHILD = 'B'
GREATGRAMPS = 'C'
UNCLES = 'U'
NEPHEWS = 'N'
COUSINS = 'D'


RELATION_CHOICES = (
    (FATHER, 'Padre'),
    (MOTHER, 'Madre'),
    (SIBLING, 'Hermano(a)'),
    (SONS, 'Hijo(a)'),
    (GRAMPS, 'Abuelo(a)'),
    (GRANDCHILD, 'Nieto(a)'),
    (GREATGRAMPS, 'Bisabuelo(a)'),
    (UNCLES, 'Tio(a)'),
    (NEPHEWS, 'Sobrino(a)'),
    (COUSINS, 'Primo(a)')
)


ACTIVE_FEED = 'A'
INACTIVE_FEED = 'I'

STATUS_CHOICES = (
    (ACTIVE_FEED, 'Vivo'),
    (INACTIVE_FEED, 'Fallecido'),
)

AGE = (('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'),
       ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'),
       ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'),
       ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'),
       ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'),
       ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'),
       ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'),
       ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50'),
       ('51', '51'), ('52', '52'), ('53', '53'), ('54', '54'), ('55', '55'), ('56', '56'),
       ('57', '57'), ('58', '58'), ('59', '59'), ('60', '60'), ('61', '61'), ('62', '62'),
       ('63', '63'), ('64', '64'), ('65', '65'), ('66', '66'), ('67', '67'), ('68', '68'),
       ('69', '69'), ('70', '70'), ('71', '71'), ('72', '72'), ('73', '73'), ('74', '74'),
       ('75', '75'), ('76', '76'), ('77', '77'), ('78', '78'), ('79', '79'), ('80', '80'),
       ('81', '81'), ('82', '82'), ('83', '83'), ('84', '84'), ('85', '85'), ('86', '86'),
       ('87', '87'), ('88', '88'), ('89', '89'), ('90', '90'), ('91', '91'), ('92', '92'),
       ('93', '93'), ('94', '94'), ('95', '95'), ('96', '96'), ('97', '97'), ('98', '98'),
       ('99', '99'), ('100', '100'), ('101', '101'), ('102', '102'), ('103', '103'), ('104', '104'),
       ('105', '105'), ('106', '106'), ('107', '107'), ('108', '108'), ('109', '109'),
       ('110', '110'), ('111', '111'), ('112', '112'), ('113', '113'), ('114', '114'),
       ('115', '115'), ('116', '116'), ('117', '117'), ('118', '118'), ('119', '119'))

class Relative(models.Model):

    class Meta:
        verbose_name = "Relative "
        verbose_name_plural = "Relative"

    first_name = models.CharField(max_length=250, verbose_name="Nombre")
    last_name = models.CharField(max_length=250, verbose_name="Apellido")
    relation = models.CharField(max_length=250,
                                choices=RELATION_CHOICES,
                                default=FATHER,
                                verbose_name="Relación")
    patient = models.ForeignKey(Patient, null=True)
    phone_number = models.CharField(
        max_length=250,
        blank=True,
        null=True,
        verbose_name="Número de telefono")
    status = models.CharField(max_length=250,
                              choices=STATUS_CHOICES,
                              default=ACTIVE_FEED,
                              verbose_name="Estatus")

    def __str__(self):
        return self.first_name


class FamilyHistory(models.Model):


    class Meta:
        verbose_name = "Family History"
        verbose_name_plural = "Family History"

    patient = models.ForeignKey(Patient, null=True)
    diagnosis = models.CharField(max_length=250, verbose_name="Condición")
    private = models.BooleanField(default=True, verbose_name="Estado")
    relative = models.ForeignKey(Relative, null=True, verbose_name="Familiar", blank=True)
    diagnosis_code = models.CharField(max_length=250, blank=True, null=True)
    age_at_onset = models.IntegerField(verbose_name="Edad de Inicio",
                                       blank=True, null=True, choices=AGE)

    def __str__(self):
        return self.diagnosis

emn/familyhistory/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm, RadioSelect, TypedChoiceField
from django.forms.widgets import HiddenInput
from .models import Relative, FamilyHistory


class RelativeCreateUpdateForm(ModelForm):
    """
    Form that creates and edits patient`s Relatives
    """
    class Meta:
        model = Relative
        fields = ('first_name',
                  'last_name',
                  'relation',
                  'phone_number',
                  'status',)


class FamilyHistoryCreateUpdateForm(ModelForm):
    """
    Form that creates and edits patient`s Family History
    """
    YESNO_CHOICES = (('0', 'Compartido'), ('1', 'Privado'))
    private = TypedChoiceField(choices=YESNO_CHOICES, widget=RadioSelect, label='Estado',
                               help_text='La información marcada como privada no puede ser accedida por el personal médico')

    def __init__(self, *args, **kwargs):
        patient = kwargs.pop('patient', None)
        super(FamilyHistoryCreateUpdateForm, self).__init__(*args, **kwargs) # populates the post
        self.fields['relative'].queryset = Relative.objects.filter(patient=patient)

    class Meta:
        model = FamilyHistory
        fields = ('diagnosis',
                  'diagnosis_code',
                  'relative',
                  'age_at_onset',
                  'private',)
        widgets = {'diagnosis_code': HiddenInput}

emn/familyhistory/views.py
from django.views.generic import CreateView, ListView, UpdateView, DeleteView

from django.core.urlresolvers import reverse_lazy

from django.db import transaction

from django.contrib.messages.views import SuccessMessageMixin

from patients.models import Patient

from contrib.views import AddPatientCreateMixin, ListPatientObjectsMixin, AlertMessagesMixin, CheckPatientMixin

from logs.views import RegisterActionMixing

from .models import Relative, FamilyHistory

from .forms import RelativeCreateUpdateForm, FamilyHistoryCreateUpdateForm
# Create your views here.


class RelativeCreateView(CheckPatientMixin, SuccessMessageMixin, AlertMessagesMixin, RegisterActionMixing, AddPatientCreateMixin, CreateView):
    model_class = Relative
    template_name = 'relatives/create-edit.html'
    form_class = RelativeCreateUpdateForm
    success_url = reverse_lazy('familyhistory:list-relative')
    success_message = "%(first_name)s fue creado satisfactoriamente"


class RelativeListView(CheckPatientMixin, ListPatientObjectsMixin, AlertMessagesMixin, ListView):
    model = Relative
    template_name = 'relatives/list.html'
    context_object_name = 'relatives'

    def get_context_data(self, **kwargs):
        user = self.request.user
        ctx = super(RelativeListView, self).get_context_data(**kwargs)
        patient = Patient.objects.filter(user=user)
        try:
            familyhistory = FamilyHistory.objects.filter(patient=patient)
            ctx['family_history'] = familyhistory
        except:
            pass
        return ctx


class RelativeUpdateView(CheckPatientMixin, SuccessMessageMixin, AlertMessagesMixin, RegisterActionMixing, UpdateView):
    model = Relative
    template_name = 'relatives/create-edit.html'
    form_class = RelativeCreateUpdateForm
    success_url = reverse_lazy('familyhistory:list-relative')
    success_message = "%(first_name)s fue editado satisfactoriamente"



class RelativeDeleteView(DeleteView):
    model = Relative
    form_class = RelativeCreateUpdateForm
    success_url = reverse_lazy('familyhistory:list-relative')
    

class FamilyHistoryCreateView(CheckPatientMixin, SuccessMessageMixin, AlertMessagesMixin, RegisterActionMixing, AddPatientCreateMixin, CreateView):
    model_class = FamilyHistory
    template_name = 'familyhistory/create-edit.html'
    form_class = FamilyHistoryCreateUpdateForm
    success_url = reverse_lazy('familyhistory:list-relative')
    success_message = "%(diagnosis)s fue creado satisfactoriamente"
    def get_form_kwargs(self):
        kwargs = super(FamilyHistoryCreateView, self).get_form_kwargs()
        patient = Patient.objects.get(user=self.request.user)
        kwargs.update({'patient': patient})
        return kwargs


class FamilyHistoryUpdateView(CheckPatientMixin, SuccessMessageMixin, AlertMessagesMixin, RegisterActionMixing, UpdateView):
    model = FamilyHistory
    template_name = 'familyhistory/create-edit.html'
    form_class = FamilyHistoryCreateUpdateForm
    success_url = reverse_lazy('familyhistory:list-relative')
    success_message = "%(diagnosis)s fue editado satisfactoriamente"
    def get_form_kwargs(self):
        kwargs = super(FamilyHistoryUpdateView, self).get_form_kwargs()
        kwargs.update({'patient': self.object.patient})
        return kwargs


class FamilyHistoryDeleteView(DeleteView):
    model = FamilyHistory
    form_class = FamilyHistoryCreateUpdateForm
    success_url = reverse_lazy('familyhistory:list-relative')

emn/familyhistory/templates/relatives/create-edit.html
{% extends "emn/base.html" %}
{% load bootstrap3 %}

{% block title %} Insertar o Editar Familiar {% endblock title %}

{% block content %}
    
            <form id="relative" method="POST">
                {% csrf_token %}
                <h1>Familiares</h1>
                <div>
                    {% bootstrap_form form  %}
                </div>
                <div>
                    <button type="submit" class="btn btn-default">Guardar Cambios</button>
                </div>
                
                <div class="clearfix"></div>
            </form>

{% endblock content %}


{% block pagejs %}
<script>
    $( document ).ready(function() {
        $( document ).ready(function() {
            $("#id_phone_number").inputmask({mask: "{{ phone }}", removeMaskOnSubmit: true});
        })
    });
    $.validator.setDefaults({
        highlight: function(element) {
            $(element).closest('.form-group').addClass('has-error');
        },
        unhighlight: function(element) {
            $(element).closest('.form-group').removeClass('has-error');
        },
        errorElement: 'span',
        errorClass: 'help-block',
        errorPlacement: function(error, element) {
            if(element.parent('.input-group').length) {
                error.insertAfter(element.parent());
            } else {
                error.insertAfter(element);
            }
        }
    });

    $(document).ready(function() {
        jQuery.extend(jQuery.validator.messages, {
            required: "Este campo es obligatorio.",
            remote: "Por favor, rellena este campo.",
            email: "Por favor, escribe una dirección de correo válida",
            url: "Por favor, escribe una URL válida.",
            date: "Por favor, escribe una fecha válida.",
            dateISO: "Por favor, escribe una fecha (ISO) válida.",
            number: "Por favor, escribe un número entero válido.",
            digits: "Por favor, escribe sólo dígitos.",
            creditcard: "Por favor, escribe un número de tarjeta válido.",
            equalTo: "Por favor, escribe el mismo valor de nuevo.",
            accept: "Por favor, escribe un valor con una extensión aceptada.",
            maxlength: jQuery.validator.format("Por favor, no escribas más de {0} caracteres."),
            minlength: jQuery.validator.format("Por favor, no escribas menos de {0} caracteres."),
            rangelength: jQuery.validator.format("Por favor, escribe un valor entre {0} y {1} caracteres."),
            range: jQuery.validator.format("Por favor, escribe un valor entre {0} y {1}."),
            max: jQuery.validator.format("Por favor, escribe un valor menor o igual a {0}."),
            min: jQuery.validator.format("Por favor, escribe un valor mayor o igual a {0}.")
        });
    });



    $("#relative").validate({
    });
</script>
{% endblock pagejs %}

emn/familyhistory/templates/relatives/list.html
{% extends "emn/base.html" %} 
{% load bootstrap3 %} 
{% load static %}

{% block pagecss %}

{% endblock pagecss %}
{% block title %} Listar Patologías de orígen Familiar {% endblock title %}
{% block content %}
        <div class="x_panel">
            <div class="x_title">
                <h2>Familiares</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a href="{% url 'familyhistory:create-relative' %}"><i class="fa fa-plus"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="table-responsive">
                    <table class="table table-striped table-hover" id="table-relative">
                        <thead>
                            <th class="col-md-3">Nombre y apellidos</th>
                            <th class="col-md-2">Relación</th>
                            <th class="col-md-3">Número de telefono</th>                                              
                            <th class="col-md-2">Estatus</th>
                            <th class="col-md-2">Acciones</th>
                        </thead>
                        <tbody>
                            {% for relative in relatives %}
                            <tr>
                                <td class="col-md-3">{{ relative.first_name }} {{ relative.last_name }}</td>
                                <td class="col-md-2">{{ relative.get_relation_display }}</td>
                                <td class="col-md-2">{{ relative.phone_number }}</td>
                                <td class="col-md-3">{{ relative.get_status_display }}</td>
                                <td class="col-md-2">
                                    <div class="dropdown">
                                        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Acciones
                                        <span class="caret"></span></button>
                                        <ul class="dropdown-menu">
                                            <li><a href="#" class="delete-object" data-target="#deleteModal" data-toggle="modal" data-url-delete="{% url 'familyhistory:delete-relative' relative.pk %}">Eliminar</a></li>
                                            <li><a href="{% url 'familyhistory:edit-relative' relative.pk %}">Editar</a></li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="x_panel">
            <div class="x_title">
                <h2>Patologías de orígen Familiar</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a href="{% url 'familyhistory:create-familyhistory' %}"><i class="fa fa-plus"></i></a></li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="table-responsive">
                    <table class="table table-striped table-hover" id="table-familyhistory">
                        <thead>
                            <th>Condición</th>
                            <th>Código</th>
                            <th>Estado</th>
                            <th>Pariente</th>                                              
                            <th>Edad</th>
                            <th>Acciones</th>
                        </thead>
                        <tbody>
                            {% for familyhistory in family_history %}
                            <tr>
                                <td>{{ familyhistory.diagnosis }}</td>
                                <td>{{ familyhistory.diagnosis_code }}</td>
                                {% if  familyhistory.private == True %}
                                <td>Privado</td>                                                        
                                {% else %}
                                <td>Compartido</td>
                                {% endif %}
                                {% if familyhistory.relative %}
                                <td>{{ familyhistory.relative }}</td>
                                {% else %}
                                <td></td>
                                {% endif %}
                                <td>{{ familyhistory.age_at_onset }}</td>
                                <td>
                                    <div class="dropdown">
                                        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Acciones
                                        <span class="caret"></span></button>
                                        <ul class="dropdown-menu">
                                            <li><a href="#" class="delete-object" data-target="#deleteModal" data-toggle="modal" data-url-delete="{% url 'familyhistory:delete-familyhistory' familyhistory.pk %}">Eliminar</a></li>
                                            <li><a href="{% url 'familyhistory:edit-familyhistory' familyhistory.pk %}">Editar</a></li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
<div id="deleteModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Eliminar</h4>
            </div>
            <div class="modal-body">
                <p>¿Está seguro de que desea eliminar permanentemente el elemento especificado? </p>
                <form method="POST" id="form-del" action="">
                {% csrf_token %}
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                        <input type="submit" class="btn btn-danger" value="Eliminar">
                    </div>
                </form>
            </div>
            
        </div>
    </div>
</div>

{% endblock content %}

{% block pagejs %}
<script type="text/javascript"> 
    $(document).ready(function () {
        $(".delete-object").click( 
            function(){
                $(this).attr('data-url-delete');
                $('#form-del').attr('action', $(this).attr('data-url-delete'));
            }
        )
    });   
</script>
{% endblock pagejs %}