emn/alerts/urls.py
from django.conf.urls import url

from contrib.views import autocomplete_view

from .models import Substance, Reaction
from .views import AlertCreateView, AlertListView, AlertDeleteView, AlertUpdateView

urlpatterns = [
    url(r'^insertar/$', AlertCreateView.as_view(), name='create-alert'),
    url(r'^listar/$', AlertListView.as_view(), name='list-alert'),
    url(r'^editar/(?P<pk>[0-9]+)/$', AlertUpdateView.as_view(), name='edit-alert'),
    url(r'^borrar/(?P<pk>[0-9]+)/$', AlertDeleteView.as_view(), name='delete-alert'),
    url(r'^substance/$', autocomplete_view, {'model': Substance}, name='substance'),
    url(r'^reaction/$', autocomplete_view, {'model': Reaction}, name='reaction'),
]

emn/emn/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^usuarios/', include('users.urls', namespace='users')),
    url(r'^', include('dashboard.urls', namespace='dashboard')),
    url(r'^paciente/', include('patients.urls', namespace='patients')),
    url(r'^paciente/enfermedades/', include('problems.urls', namespace='problems')),
    url(r'^paciente/alertas/', include('alerts.urls', namespace='alerts')),
    url(r'^paciente/procedimientos/', include('procedures.urls', namespace='procedures')),
    url(r'^paciente/medicamentos/', include('medications.urls', namespace='medications')),
    url(r'^paciente/historia-familiar/', include('familyhistory.urls', namespace='familyhistory')),
    url(r'^personal/paciente/', include('personnel.urls', namespace='personnel')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

emn/medications/urls.py
from django.conf.urls import url
from contrib.views import autocomplete_view
from .models import MedicationName
from .views import MedicationCreateView, MedicationListView, MedicationUpdateView, MedicationDeleteView

urlpatterns = [
    url(r'^insertar/$', MedicationCreateView.as_view(), name='create-medication'),
    url(r'^listar/$', MedicationListView.as_view(), name='list-medication'),
    url(r'^editar/(?P<pk>[0-9]+)/$', MedicationUpdateView.as_view(), name='edit-medication'),
    url(r'^borrar/(?P<pk>[0-9]+)/$', MedicationDeleteView.as_view(), name='delete-medication'),
    url(r'^medication/$', autocomplete_view, {'model': MedicationName}, name='medication'),
]

emn/patients/urls.py
from django.conf.urls import url

from .views import (PatientUpdateView, PatientDetailView, PatientEmergencyDetailView,
                    PatientEmergencyPdfView, ContactUpdateView, EmergencyCodeView,
                    PatientEmergencyMiniPdfView)

urlpatterns = [
    url(r'^emergencia/codigo/$', EmergencyCodeView.as_view(), name='emergency-code'),
    url(r'^editar/$', PatientUpdateView.as_view(), name='edit-patient'),
    url(r'^contacto/$', ContactUpdateView.as_view(), name='contact'),
    url(r'^perfil/$', PatientDetailView.as_view(), name='profile-patient'),
    url(r'^emergencia/$', PatientEmergencyDetailView.as_view(), name='emergency-patient'),
    url(r'^pdf/$', PatientEmergencyPdfView.as_view(), name='emergency-pdf'),
    url(r'^pdf/mini/$', PatientEmergencyMiniPdfView.as_view(), name='emergency-pdf-mini'),

]

emn/problems/urls.py
from django.conf.urls import url

from contrib.views import autocomplete_view

from .models import Condition
from .views import ProblemCreateView, ProblemListView, ProblemUpdateView, ProblemDeleteView

urlpatterns = [
    url(r'^insertar/$', ProblemCreateView.as_view(), name='create-problem'),
    url(r'^listar/$', ProblemListView.as_view(), name='list-problem'),
    url(r'^editar/(?P<pk>[0-9]+)/$', ProblemUpdateView.as_view(), name='edit-problem'),
    url(r'^borrar/(?P<pk>[0-9]+)/$', ProblemDeleteView.as_view(), name='delete-problem'),
    url(r'^condition/$', autocomplete_view, {'model': Condition}, name='condition'),
]

emn/procedures/urls.py
from django.conf.urls import url
from contrib.views import autocomplete_view
from .models import ProcedureNameCode

from .views import ProcedureCreateView, ProcedureListView, ProcedureUpdateView, ProcedureDeleteView

urlpatterns = [
    url(r'^insertar/$', ProcedureCreateView.as_view(), name='create-procedure'),
    url(r'^listar/$', ProcedureListView.as_view(), name='list-procedure'),
    url(r'^editar/(?P<pk>[0-9]+)/$', ProcedureUpdateView.as_view(), name='edit-procedure'),
    url(r'^borrar/(?P<pk>[0-9]+)/$', ProcedureDeleteView.as_view(), name='delete-procedure'),
    url(r'^procedure/$', autocomplete_view, {'model': ProcedureNameCode}, name='procedure'),
]

emn/patients/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext as _
from django.utils.crypto import get_random_string


from emn.settings import AUTH_USER_MODEL


# Create your models here.


A = 'A'
B = 'B'
AB = 'AB'
O = 'O'

BLOOD_TYPE = (
    (A, 'A'),
    (B, 'B'),
    (AB, 'AB'),
    (O, 'O'),
)

NEGATIVE = '-'
POSITIVE = '+'

RHESUS_FACTOR = (
    (NEGATIVE, '-'),
    (POSITIVE, '+'),
)

class Patient(models.Model):
    user = models.OneToOneField(AUTH_USER_MODEL, on_delete=models.CASCADE,
                                related_name='user')
    emergency_code = models.CharField(max_length=50,
                                      verbose_name='Código',
                                      default=get_random_string(
                                          length=12,
                                          allowed_chars='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'))
    first_name = models.CharField(max_length=500,
                                  verbose_name='Nombre',
                                  blank=False,
                                  null=False)
    last_name = models.CharField(max_length=500,
                                 verbose_name='Apellido',
                                 blank=False,
                                 null=False)
    date_of_birth = models.DateField(null=False,
                                     verbose_name='Fecha de nacimiento',
                                     blank=False,)
    blood_type = models.CharField(
        max_length=2,
        choices=BLOOD_TYPE,
        verbose_name='Grupo sanguíneo', null=True, blank=True
    )
    rhesus_factor = models.CharField(
        max_length=2,
        choices=RHESUS_FACTOR,
        verbose_name='Factor rh', null=True, blank=True
    )
    identity_document = models.CharField(max_length=100,
                                         verbose_name='Documento de Identificación',
                                         null=True,
                                         blank=True)
    phone_number = models.CharField(max_length=50,
                                    verbose_name='Número de teléfono',
                                    null=True, blank=True)
    gender = models.CharField(
        max_length=50,
        choices=(
            ('F', _('Femenino')),
            ('M', _('Masculino')),
        ),
        verbose_name='Sexo', null=True, blank=False
    )
    nationality = models.CharField(
        max_length=50,
        choices=(
            ('V', _('Venezolano')),
            ('E', _('Extranjero'))
        ),
        verbose_name='Nacionalidad', null=True, blank=True
    )
    occupation = models.TextField(verbose_name='Ocupación', null=True,
                                  blank=True)
    home_address = models.TextField(verbose_name='Dirección de Habitación',
                                    null=True, blank=True)
    contact_first_name = models.CharField(max_length=500,
                                          verbose_name='Nombre',
                                          blank=False,
                                          null=True)
    contact_last_name = models.CharField(max_length=500,
                                         verbose_name='Apellido',
                                         blank=False,
                                         null=True)
    contact_phone_number = models.CharField(max_length=50,
                                            verbose_name='Número de teléfono',
                                            null=True, blank=False)
    card_created = models.BooleanField(
        default=True,
        verbose_name="card created"
        )
    birth_certificate_number = models.PositiveIntegerField(
        verbose_name='Número del Acta de Nacimiento',
        null=True, blank=True)
    birth_certificate_folio_number = models.PositiveIntegerField(verbose_name='Número de Tomo',
                                                                 null=True, blank=True)
    birth_certificate_volume_number = models.PositiveIntegerField(verbose_name='Número de Folio',
                                                                  null=True, blank=True)
    birth_certificate_book_number = models.PositiveIntegerField(verbose_name='Número de Libro',
                                                                null=True, blank=True)
    # father_first_name = models.CharField(max_length=500,
    #                                      verbose_name='Nombre del padre',
    #                                      blank=False,
    #                                      null=False)
    # father_last_name = models.CharField(max_length=500,
    #                                     verbose_name='Apellido del padre',
    #                                     blank=False,
    #                                     null=False)
    # father_identity_document = models.CharField(
    #     max_length=100,
    #     verbose_name='Documento de Identificación del padre',
    #     null=True,
    #     blank=True)
    # mother_first_name = models.CharField(max_length=500,
    #                                      verbose_name='Nombre de la madre',
    #                                      blank=False,
    #                                      null=False)
    # mother_last_name = models.CharField(max_length=500,
    #                                     verbose_name='Apellido de la madre',
    #                                     blank=False,
    #                                     null=False)
    # mother_identity_document = models.CharField(
    #     max_length=100,
    #     verbose_name='Documento de Identificación de la madre',
    #     null=True,
    #     blank=True)

emn/patients/forms.py
# -*- coding: utf-8 -*-
from datetime import datetime
from .models import Patient

from django.forms import BaseInlineFormSet, inlineformset_factory, ModelForm, ValidationError

from users.forms import PatientCreationForm

from users.models import PatientProxy



class PatientDemographicEditForm(ModelForm):
    """
    Form that edits Patient`s demographic information
    """
    class Meta:
        model = Patient
        fields = ('first_name', 'last_name', 'identity_document', 'date_of_birth', 'gender',
                  'blood_type', 'rhesus_factor', 'phone_number', 'nationality', 'occupation',
                  'home_address', 'birth_certificate_number', 'birth_certificate_folio_number',
                  'birth_certificate_volume_number', 'birth_certificate_book_number')


    def clean_rhesus_factor(self):

        blood_type = self.cleaned_data.get("blood_type")
        rhesus_factor = self.cleaned_data.get("rhesus_factor")
        if rhesus_factor:
            if not blood_type:
                raise ValidationError(
                    'No se puede introducir un factor Rh sin un grupo sanguíneo')
        return self.cleaned_data.get("rhesus_factor")

    def clean_date_of_birth(self):
        date_of_birth = self.cleaned_data.get("date_of_birth")
        if date_of_birth:
            if date_of_birth > datetime.date(datetime.now()):
                raise ValidationError(
                    'No se puede introducir una fecha de nacimiento en el futuro')
        return self.cleaned_data.get("date_of_birth")

    def clean(self):
        # Check that 'birth_certificate_number',
        # 'birth_certificate_folio_number', 'birth_certificate_volume_number',
        # 'birth_certificate_book_number' exist together
        super(PatientDemographicEditForm, self).clean()
        birth_certificate_number = self.cleaned_data.get(
            "birth_certificate_number")
        birth_certificate_folio_number = self.cleaned_data.get(
            "birth_certificate_folio_number")
        birth_certificate_volume_number = self.cleaned_data.get(
            "birth_certificate_volume_number")
        birth_certificate_book_number = self.cleaned_data.get(
            "birth_certificate_book_number")

        if (birth_certificate_number or birth_certificate_folio_number
                or birth_certificate_volume_number or birth_certificate_book_number):
            if not (birth_certificate_number and birth_certificate_folio_number
                    and birth_certificate_volume_number and birth_certificate_book_number):
                e = ValidationError(
                    "Los Números del Acta de Nacimiento, de Tomo, de Folio, de Libro deben ser llenados")
                self.add_error(None, e)
                if any(self.errors):
                    print(self.errors)





class PatientEmergencyContact(ModelForm):
    """
    Form that edits Patient`s emergency contact information
    """
    class Meta:
        model = Patient
        fields = ('contact_first_name', 'contact_last_name', 'contact_phone_number')

emn/patients/templates/patients/pdf-emergency-mini.html
{% extends "emn/pdf.html" %} 


{% block title %} Tarjeta de Emergencia {% endblock title %}
{% block content %}
<div id="outer">
    <div id="inner">
        <strong>
            <h3>Tarjeta de Emergencia</h3>
            <p> 
                Información disponible en:
                <font style="color:blue">{{ domain }} </font>
                <br>
                <br>
                Usuario:<font style="color:red"> {{ user.username }} </font>
                <br>
                Clave:<font style="color:red"> {{ patient.emergency_code }} </font>
                <br>         
            </p> 
        </strong>
        <div class="row">
            <font size="1">
                <span class="sign"> Yo (Nombre y Apellido): <span class="line"></span></span>
                <span class="sign">
                    posesor del Documento de Identificación <br>(Documento de Identificación): 
                    <span class = "line"></span>
                </span>
                <span class="completed-by">
                    Garantizo que la Información reflejada en el sistema y en 
                    la Tarjeta de Emergencia fue rellenada por mi persona
                </span>
                <span class="sign">Firma: <span class = "line"></span></span>  
            </font>
        </div>
        <table class="table">
            <tbody>
                <tr>
                    <td><strong>Paciente:</strong></td>
                    <td>{{ patient.first_name }} {{ patient.last_name }}</td>
                </tr>
                <tr>
                    {% if patient.identity_document %}
                    <td><strong>Documento de Identificación</strong></td>
                    <td>{{ patient.identity_document }}</td>
                    {% else %}
                    <td><strong>Documento de Identificación</strong></td>
                    <td></td>
                    {% endif %}
                </tr>
                <tr>
                    <td><strong>Fecha de nacimiento:</strong></td>
                    <td>{{ patient.date_of_birth|date:"d/m/Y"}}</td>
                </tr>
                <tr>
                    <td><strong>Sexo</strong></td>
                    <td>{{ patient.get_gender_display }}</td>
                </tr>
                {% if patient.blood_type %}
                <tr>
                    <td><strong>Tipo de sangre:</strong></td>
                    <td>{{ patient.get_blood_type_display }}</td>
                </tr>
                {% else %}
                {% endif %}
                {% if patient.rhesus_factor %}
                <tr>
                    <td><strong>Factor Rh:</strong></td>
                    <td>{{ patient.get_rhesus_factor_display }}</td>
                </tr>
                {% else %}
                {% endif %}
                {% if patient.nationality %}
                <tr>
                    <td><strong>Nacionalidad:</strong></td>
                    <td>{{ patient.get_nationality_display }}</td>
                </tr>
                {% else %} 
                {% endif %} 
                {% if patient.occupation %}
                <tr>
                    <td><strong>Ocupación:</strong></td>
                    <td>{{ patient.occupation }}</td>
                </tr>
                {% else %} 
                {% endif %} 
                {% if patient.home_address %}
                <tr>
                    <td><strong>Dirección:</strong></td>
                    <td>{{ patient.home_address }}</td>
                </tr>
                {% else %} 
                {% endif %} 
                {% if patient.phone_number %}
                <tr>
                    <td><strong>Número de teléfono:</strong></td>
                    <td>{{ patient.phone_number }}</td>
                </tr>
                {% else %} 
                {% endif %}
                {% if patient.birth_certificate_number %}
                <tr>
                    <td><strong>Número del Acta de Nacimiento :</strong></td>
                    <td>{{ patient.birth_certificate_number }}</td>
                </tr>
                {% else %}
                {% endif %}
                {% if patient.birth_certificate_folio_number %}
                <tr>
                    <td><strong>Número de Tomo del Acta de Nacimiento:</strong></td>
                    <td>{{ patient.birth_certificate_folio_number }}</td>
                </tr>
                {% else %}
                {% endif %}
                {% if patient.birth_certificate_volume_number %}
                <tr>
                    <td><strong>Número de Folio del Acta de Nacimiento:</strong></td>
                    <td>{{ patient.birth_certificate_volume_number }}</td>
                </tr>
                {% else %}
                {% endif %}
                {% if patient.birth_certificate_book_number %}
                <tr>
                    <td><strong>Número de Libro del Acta de Nacimiento:</strong></td>
                    <td>{{ patient.birth_certificate_book_number }}</td>
                </tr>
                {% else %}
                {% endif %}
            </tbody>
        </table>

        {% if patient.contact_phone_number or patient.contact_first_name or patient.contact_last_name %}
        <div class="row">
            <div class="">
                <h4> Contacto de Emergencia: </h4>
                <p>
                    <strong> Nombre: </strong> 
                    {% if patient.contact_first_name %} 
                    {{ patient.contact_first_name }} 
                    {% else %} 
                    {%endif %}
                    <strong>Apellido:</strong> 
                    {% if patient.contact_last_name %} 
                    {{ patient.contact_last_name }} 
                    {% else %} 
                    {% endif%}
                    <strong>Telefono:</strong>
                    {% if patient.contact_phone_number %} 
                    {{ patient.contact_phone_number }} 
                    {% else %}
                {% endif %}
                </p>
            </div>
        </div>
        {% endif %}
        
    </div>
    
</div>
{% endblock content %} 



{% block pagestyles %}
<style>
    ul {
        word-wrap: break-word;
        word-break: break-all;
        padding-left:0.15in;
    }
    table {
        word-wrap: break-word;
        word-break: break-all;
        table-layout: fixed;
        width: 3.65in;
    }
    
    #outer {
        position: relative;
        width: 3.75in;
        word-wrap: break-word;
        border-style: dotted;
    }
    #inner {
        padding: 0.1in;
    }

    /* signature & title part */
    .completed-by, .signature, .sign { float: left; }

    /* phone & date part */
    .sign > .line {
    display: inline-block;
    border-bottom: 1px solid #000;
    width: 175px; 
    }
</style>

{% endblock pagestyles %}

emn/patients/templates/patients/profile.html
{% extends "emn/base.html" %} {% load bootstrap3 %} 


{% block title %} Perfil {% endblock title %}
{% block content %}
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Información Demográfica  <a href="{% url 'patients:edit-patient' %}"><i class="fa fa-edit"></i></a></h2>
            </div>
            <div class="x_content">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <table class=" table basic">
                        <tbody>
                            <tr>
                                <td><strong>Paciente:</strong></td>
                                <td>{{ patient.first_name }} {{ patient.last_name }}</td>
                            </tr>
                            <tr>
                                {% if patient.identity_document %}
                                    <td><strong>Documento de Identificación</strong></td>
                                    <td>{{ patient.identity_document }}</td>
                                {% else %}
                                    <td><strong>Documento de Identificación</strong></td>
                                    <td></td>
                                {% endif %}
                            </tr>
                            <tr>
                                <td><strong>Fecha de nacimiento:</strong></td>
                                <td>{{ patient.date_of_birth }}</td>
                            </tr>
                            <tr>
                                <td><strong>Sexo</strong></td>
                                <td>{{ patient.get_gender_display }}</td>
                            </tr>
                            {% if patient.blood_type %}
                            <tr>
                                <td><strong>Tipo de sangre:</strong></td>
                                <td>{{ patient.get_blood_type_display }}</td>
                            </tr>
                            {% else %}
                            {% endif %}
                            {% if patient.rhesus_factor %}
                            <tr>
                                <td><strong>Factor Rh:</strong></td>
                                <td>{{ patient.get_rhesus_factor_display }}</td>
                            </tr>
                            {% else %}
                            {% endif %}
                            {% if patient.nationality %}
                            <tr>
                                <td><strong>Nacionalidad:</strong></td>
                                <td>{{ patient.get_nationality_display }}</td>
                            </tr>
                            {% else %}
                            {% endif %}
                            {% if patient.occupation %}
                            <tr>
                                <td><strong>Ocupación:</strong></td>
                                <td>{{ patient.occupation }}</td>
                            </tr>
                            {% else %}
                            {% endif %}
                            {% if patient.home_address %}
                            <tr>
                                <td><strong>Dirección de Habitación:</strong></td>
                                <td>{{ patient.home_address }}</td>
                            </tr>
                            {% else %}
                            {% endif %}
                            {% if patient.phone_number %}
                            <tr>
                                <td><strong>Número de teléfono:</strong></td>
                                <td>{{ patient.phone_number }}</td>
                            </tr>
                            {% else %}
                            {% endif %}
                            {% if patient.birth_certificate_number %}
                            <tr>
                                <td><strong>Número del Acta de Nacimiento :</strong></td>
                                <td>{{ patient.birth_certificate_number }}</td>
                            </tr>
                            {% else %}
                            {% endif %}
                            {% if patient.birth_certificate_folio_number %}
                            <tr>
                                <td><strong>Número de Tomo del Acta de Nacimiento:</strong></td>
                                <td>{{ patient.birth_certificate_folio_number }}</td>
                            </tr>
                            {% else %}
                            {% endif %}
                            {% if patient.birth_certificate_volume_number %}
                            <tr>
                                <td><strong>Número de Folio del Acta de Nacimiento:</strong></td>
                                <td>{{ patient.birth_certificate_volume_number }}</td>
                            </tr>
                            {% else %}
                            {% endif %}
                            {% if patient.birth_certificate_book_number %}
                            <tr>
                                <td><strong>Número de Libro del Acta de Nacimiento:</strong></td>
                                <td>{{ patient.birth_certificate_book_number }}</td>
                            </tr>
                            {% else %}
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% if  patient.contact_phone_number or patient.contact_first_name or patient.contact_last_name %}
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <h3> Contacto de Emergencia: </h3>
            <br>
            <strong> Nombre: </strong>
            {% if patient.contact_first_name %}
                {{ patient.contact_first_name }}
            {% else %}
            {% endif %}
            <strong>Apellido:</strong> 
            {% if patient.contact_last_name %}
                {{ patient.contact_last_name }}         
            {% else %}
            {% endif %}
            <strong>Telefono:</strong>
            {% if patient.contact_phone_number %}
                {{ patient.contact_phone_number }}        
            {% else %}
            {% endif %}
        </div>
    </div>
{% endif %}

<div class="row">
    <div class="col-md-4 col-sm-4 col-xs-12 block">
        <div class="x_panel">
            <div class="x_title">
                <h3>Enfermedades <a href="{% url 'problems:create-problem' %}"><i class="fa fa-plus"></i></a></h3>
                <ul class="nav navbar-right panel_toolbox">
                </ul>
            </div>
            <div class="x_content">
                <ul>
                    {% for problem in problems %} 
                        <li><a href="{% url 'problems:edit-problem' problem.pk %}">{{ problem.condition }}</a></li> 
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-sm-4 col-xs-12 block">
        <div class="x_panel">
            <div class="x_title">
                <h3>Alertas y Alergias <a href="{% url 'alerts:create-alert' %}"><i class="fa fa-plus"></i></a></h3>
                <ul class="nav navbar-right panel_toolbox">
                </ul>
            </div>
            <div class="x_content">
                <ul>
                    {% for alert in alerts %}
                        <li><a href="{% url 'alerts:edit-alert' alert.pk %}">{{ alert.substance }}</a> </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-sm-4 col-xs-12 block">
        <div class="x_panel">
            <div class="x_title">
                <h3>Medicamentos <a href="{% url 'medications:create-medication' %}"><i class="fa fa-plus"></i></a></h3>
                <ul class="nav navbar-right panel_toolbox">
                </ul>
            </div>
            <div class="x_content">
                <ul>
                    {% for medication in medications %} 
                        <li><a href="{% url 'medications:edit-medication' medication.pk %}">{{ medication.medication }}</a></li> 
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4 col-sm-4 col-xs-12 block">
        <div class="x_panel">
            <div class="x_title">
                <h3>Intervenciones Médicas <a href="{% url 'procedures:create-procedure' %}"><i class="fa fa-plus"></i></a></h3>
                <ul class="nav navbar-right panel_toolbox">
                   
                </ul>
            </div>
            <div class="x_content">
                <ul>
                    {% for procedure in procedures %} 
                        <li><a href="{% url 'procedures:edit-procedure' procedure.pk %}">{{ procedure.procedure }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-sm-4 col-xs-12 block">
        <div class="x_panel">
            <div class="x_title">
                <h3>Historia Familiar
                    {% if familyhistory %}
                        <a href="{% url 'familyhistory:create-familyhistory' %}"><i class="fa fa-plus"></i></a>
                    {% else %}
                    {% endif %}
                </h3>
                <ul class="nav navbar-right panel_toolbox">
                   
                </ul>
            </div>
            <div class="x_content">
                <ul>
                    {% for fm in familyhistory %} 
                        <li><a href="{% url 'familyhistory:edit-familyhistory' fm.pk %}">{{ fm.diagnosis }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

 {% block pagestyles %}
        <style>
        .x_content > ul {
            list-style-type: none;
            padding-left:0;
            word-wrap: break-word;
            word-break: break-all; 
            }
        table {
            word-wrap: break-word;
            word-break: break-all;
            table-layout: fixed;
        }
        </style>
      
{% endblock pagestyles %}

emn/patients/templates/patients/update_emergency_code.html
{% extends "emn/base.html" %}
{% load bootstrap3 %}

{% block title %} Nueva Clave de Emergencia {% endblock title %}
{% block content %}
    
    <form id="emergency-code" method="POST">
        {% csrf_token %}
        <h1>Clave de emergencias</h1>
        <h2>{{ patient.emergency_code }}</h2>
        
        <div>
            <button type="submit" class="btn btn-default">Generar nueva clave de emergencias</button>
        </div>
        
    </form>

{% endblock content %}


{% block pagestyles %}
<!-- Custom  Styles -->
    <style>
        .center-tittle {
            text-align: center;
            text-decoration: none;
        }
    </style>

{% endblock pagestyles %}