emn/alerts/urls.py
from django.conf.urls import url

from contrib.views import autocomplete_view

from .models import Substance, Reaction
from .views import AlertCreateView, AlertListView, AlertDeleteView, AlertUpdateView

urlpatterns = [
    url(r'^insertar/$', AlertCreateView.as_view(), name='create-alert'),
    url(r'^listar/$', AlertListView.as_view(), name='list-alert'),
    url(r'^editar/(?P<pk>[0-9]+)/$', AlertUpdateView.as_view(), name='edit-alert'),
    url(r'^borrar/(?P<pk>[0-9]+)/$', AlertDeleteView.as_view(), name='delete-alert'),
    url(r'^substance/$', autocomplete_view, {'model': Substance}, name='substance'),
    url(r'^reaction/$', autocomplete_view, {'model': Reaction}, name='reaction'),
]

emn/emn/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^usuarios/', include('users.urls', namespace='users')),
    url(r'^', include('dashboard.urls', namespace='dashboard')),
    url(r'^paciente/', include('patients.urls', namespace='patients')),
    url(r'^paciente/enfermedades/', include('problems.urls', namespace='problems')),
    url(r'^paciente/alertas/', include('alerts.urls', namespace='alerts')),
    url(r'^paciente/procedimientos/', include('procedures.urls', namespace='procedures')),
    url(r'^paciente/medicamentos/', include('medications.urls', namespace='medications')),
    url(r'^paciente/historia-familiar/', include('familyhistory.urls', namespace='familyhistory')),
    url(r'^personal/paciente/', include('personnel.urls', namespace='personnel')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

emn/patients/urls.py
from django.conf.urls import url

from .views import (PatientUpdateView, PatientDetailView, PatientEmergencyDetailView,
                    PatientEmergencyPdfView, ContactUpdateView, EmergencyCodeView,
                    PatientEmergencyMiniPdfView)

urlpatterns = [
    url(r'^emergencia/codigo/$', EmergencyCodeView.as_view(), name='emergency-code'),
    url(r'^editar/$', PatientUpdateView.as_view(), name='edit-patient'),
    url(r'^contacto/$', ContactUpdateView.as_view(), name='contact'),
    url(r'^perfil/$', PatientDetailView.as_view(), name='profile-patient'),
    url(r'^emergencia/$', PatientEmergencyDetailView.as_view(), name='emergency-patient'),
    url(r'^pdf/$', PatientEmergencyPdfView.as_view(), name='emergency-pdf'),
    url(r'^pdf/mini/$', PatientEmergencyMiniPdfView.as_view(), name='emergency-pdf-mini'),

]

emn/problems/urls.py
from django.conf.urls import url

from contrib.views import autocomplete_view

from .models import Condition
from .views import ProblemCreateView, ProblemListView, ProblemUpdateView, ProblemDeleteView

urlpatterns = [
    url(r'^insertar/$', ProblemCreateView.as_view(), name='create-problem'),
    url(r'^listar/$', ProblemListView.as_view(), name='list-problem'),
    url(r'^editar/(?P<pk>[0-9]+)/$', ProblemUpdateView.as_view(), name='edit-problem'),
    url(r'^borrar/(?P<pk>[0-9]+)/$', ProblemDeleteView.as_view(), name='delete-problem'),
    url(r'^condition/$', autocomplete_view, {'model': Condition}, name='condition'),
]

emn/users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views


from . import views

urlpatterns = [
    # create User
    url(r'^login/$', views.user_login_view,
        name='auth_login'),
    # authentication views
    url(r'^crear/$', views.PatientCreate.as_view(),
        name='auth_patient_create'),
    url(r'^editar/$', views.PatientUpdateView.as_view(),
        name='auth_patient_edit'),
    url(r'^redirect/$', views.user_redirect,
        name='auth_redirect'),
    url(r'^logout/$', auth_views.logout_then_login,
        name='auth_logout'),
    url(r'^password-change/$',
        auth_views.password_change,
        name='change_password'),
    url(r'^password-change/done/$',
        auth_views.password_change_done),
    url(r'^password-reset/$',
        auth_views.password_reset, {
            'template_name': 'users/password-reset.html',
            'email_template_name':'users/password-reset-email.html',
            'post_reset_redirect':'users:reset-password-done',
            },
        'password-reset'),
    url(r'^password-reset/done/$',
        auth_views.password_reset_done, {
            'template_name': 'users/password-reset-done.html'},
        name='reset-password-done',
       ),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        auth_views.password_reset_confirm, {
            'template_name': 'users/password-reset-confirm.html',
            'post_reset_redirect':'users:auth_login',
            },
        name='password-reset-confirm'),
    url(r'^reset/done/$',
        auth_views.password_reset_complete),
]

emn/emn/templates/emn/partials/footer.html
<footer>

    <div class="navbar navbar-default">
    <div class="container">
      <p class="navbar-text pull-left">© 2016 - Victor Ottati A.
           <a href="{% url 'dashboard:landing' %}"> EMI - Emergencias</a>
      </p>
    </div>
</footer>

emn/emn/templates/emn/partials/left-sidebar-per.html
<!-- sidebar menu -->
<div id="navbar" class="col-sm-3 col-md-2 sidebar navbar-collapse collapse" aria-expanded="false">
    <ul class="nav nav-sidebar">
        <li><a href="{% url 'personnel:emergency-search' %}"><i class="fa fa-search"></i> Buscar Paciente </a>
            </li>
        <li>
            <a href="{% url 'users:auth_logout'%}" data-toggle="tooltip" data-placement="top" title="Logout">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span> Cerrar Sesión </a>
        </li>
    </ul>
</div>
<!-- /sidebar menu -->

emn/emn/templates/emn/partials/left-sidebar.html
<!-- sidebar menu -->
<div id="navbar" class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar" aria-expanded="false">
    <ul class="nav nav-sidebar">
        <li><a href="{% url 'patients:profile-patient' %}"><i class="fa fa-home"></i> Inicio </a></li>
        <li><a href="{% url 'problems:list-problem' %}">Enfermedades</a></li>
        <li><a href="{% url 'alerts:list-alert' %}">Alertas, Alergias y Reacciones adversas</a></li>
        <li><a href="{% url 'procedures:list-procedure' %}">Intervenciones Médicas</a></li>
        <li><a href="{% url 'medications:list-medication' %}">Medicamentos</a></li>
        <li><a href="{% url 'familyhistory:list-relative' %}">Antecedentes Familiares</a></li>
        <li><a href="{% url 'users:auth_patient_edit' %}"><i class="fa fa-user"></i> Editar Información de Usuario </a></li>
        <li><a href="{% url 'patients:edit-patient' %}"><i class="fa fa-info"></i> Editar Información Personal </a></li>
        <li><a href="{% url 'patients:contact' %}"><i class="fa fa-info"></i> Editar Contacto de emergencia </a></li>  
        <li><a href="{% url 'patients:emergency-code' %}"><i class="fa fa-user"></i> Clave de Emergencias </a></li>
        <li><a href="{% url 'patients:emergency-patient' %}"><i class="fa fa-user-md"></i> Perfil de Emergencias </a></li>   
        <li><a href="{% url 'patients:emergency-pdf' %}" target="_blank"><i class="fa fa-user-md"></i> Crear Tarjeta de Emergencias </a></li>
        <li><a href="{% url 'patients:emergency-pdf-mini' %}" target="_blank"><i class="fa fa-user-md"></i> Crear Tarjeta de Emergencias pequeña</a></li>             
        <li>      
            <a href="{% url 'users:auth_logout'%}" data-toggle="tooltip" data-placement="top" title="Logout">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span> Cerrar Sesión </a>
        </li>
    </ul>
</div>
<!-- /sidebar menu -->

emn/emn/templates/emn/partials/plain-navbar.html
<div id="navbar" class="col-sm-3 col-md-2 visible-xs" aria-expanded="false">
    <ul class="nav sidebar" >
        <li><a href="{% url 'patients:profile-patient' %}"><i class="fa fa-home"></i> Inicio </a></li>
        <li>
            <a href="{% url 'users:auth_logout'%}" data-toggle="tooltip" data-placement="top" title="Logout">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span> Cerrar Sesion </a>
        </li>
    </ul>
</div>

emn/emn/templates/emn/partials/top-navigation.html
<nav class="navbar  navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false"
                aria-controls="sidebar" id="top-toggle">
                <i class="glyphicon glyphicon-align-justify"></i>
            </button>
            
            <a class="navbar-brand" href="{% url 'dashboard:landing' %}"> 
                <strong>
                    <i class="fa fa-medkit"></i>
                    {% if TITLE %}
                        {{ TITLE }}             
                    {% else %}
                        EMI
                    {% endif %}
                </strong>
            </a>
        </div>
        <div id="navbar-1" class="navbar-collapse collapse" aria-expanded="false" style="height: 1px;">
            {% if user.is_authenticated %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'users:auth_redirect' %}">Perfil: {{ user.username }}</a></li>
                    <li><a href="{% url 'users:auth_logout'%}"><i class="fa fa-sign-out"></i>Cerrar Sesión</a></li>
                </ul>
            {% endif %}
        </div>
    </div>
</nav>